version: '3.8'

services:
  # 1. SERVIÇO DO BANCO DE DADOS POSTGRESQL
  db:
    image: postgres:16
    container_name: sensorflow-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. SEU SERVIÇO DE API
  api:
    build: .
    container_name: temp-data-api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # 3. SERVIÇO DO GRAFANA
  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  grafana_data:
